; PlatformIO Project Configuration File

[platformio]
default_envs = serial_upload

[env]
platform = espressif32 @ 6.10.0   ; pins ESP32 Arduino core 2.0.17
board = esp32doit-devkit-v1
framework = arduino

board_build.filesystem = littlefs
board_build.partitions = partitions.csv

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_ldf_mode = chain
build_flags = -D ESP32_DEVKITV1
              -D DISABLE_IMAP
              -D DISABLE_SD
              -D SILENT_MODE

lib_deps =
    symlink://../../libraries/ADS1115

    Arduino_DebugUtils @ ^1.4.0
    paulstoffregen/Time @ ^1.6
    robtillaart/RunningMedian @ ^0.3.9
    br3ttb/PID @ ^1.2.1
    bblanchon/ArduinoJson @ ^7.2.0
    seithan/Easy Nextion Library @ ^1.0.6
    milesburton/DallasTemperature @ ^3.9.1
    ESP32Async/AsyncTCP @ ^3.2.0
    ESP32Async/ESPAsyncWebServer @ ^3.3.0
    bertmelis/espMqttClient @ ^1.7.0
    mobizt/ESP Mail Client @ ^3.4.19

[env:serial_upload]
debug_tool = esp-prog
debug_init_break = tbreak setup
build_type = debug
lib_deps = ${env.lib_deps}
build_flags =
    ${env.build_flags}
    -D DEVT
upload_protocol = esptool

[env:OTA_upload]
lib_deps = ${env.lib_deps}
build_flags =
    ${env.build_flags}
upload_protocol = espota
upload_port = poolmaster.local
upload_flags =
    --port=3232
    --auth=${sysenv.POOLMASTER_OTA_PWD}
